sudo: required
language: generic
services:
  - docker
before_install: 
  - docker build -t react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true react-test npm run test

affer_success:
  - docker build -t nghi/multi-client ./client
  - docker build -t nghi/multi-nginx ./nginx
  - docker build -t nghi/multi-api ./server
  - docker build -t nghi/multi-worker ./worker
  - docker ps
  - docker images -a
  - echo "$dockerpass" | docker login -u "$dockerid" --password-stdin
  - docker push nghi/multi-client
  - docker push nghi/multi-nginx
  - docker push nghi/multi-api
  - docker push nghi/multi-worker