sudo: required
language: generic
services:
  - docker
before_install: 
  - docker build -t react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true react-test npm run test

affer_success:
  - docker build -t nghi-multi-client ./client
  - docker build -t nghi-multi-nginx ./nginx
  - docker build -t nghi-multi-api ./server
  - docker build -t nghi-multi-worker ./worker
  - docker ps
  - docker images -a
  - docker logout
  - echo "$dockerpass" | docker login -u "$dockerid" --password-stdin
  - docker tag nghi-multi-client nguyenduynghi2001/nghi-multi-client
  - docker push nguyenduynghi2001/nghi-multi-client
  - docker tag nghi-multi-nginx nguyenduynghi2001/nghi-multi-nginx
  - docker push nguyenduynghi2001/nghi-multi-nginx
  - docker tag nghi-multi-api nguyenduynghi2001/nghi-multi-api
  - docker push nguyenduynghi2001/nghi-multi-api
  - docker tag nghi-multi-worker nguyenduynghi2001/nghi-multi-worker
  - docker push nguyenduynghi2001/nghi-multi-worker
  - docker image -a

deploy:
  provider: elasticbeantalk
  region: us-east-1
  app: docker-multi
  env: Dockermulti-env-1
  bucket_name: elasticbeanstalk-us-east-1-117155957847
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWX_SECRETKEY"