sudo: required
service:
  - docker
before_install: 
  - docker build -t react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run react-test npm test -- --coverage

affer_success:
  - docker build -t nghi/multi-client ./client
  - docker build -t nghi/multi-nginx ./nginx
  - docker build -t nghi/multi-api ./server
  - docker build -t nghi/multi-worker ./worker
  - echo "$dockerpass" | docker login -u "$dockerid" --password-stdin
  - docker push nghi/multi-client
  - docker push nghi/multi-nginx
  - docker push nghi/multi-api
  - docker push nghi/multi-worker