version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
  redis:
    image: 'redis:latest'
    restart: always
  api:
    build: 
      dockerfile: Dockerfile
      context: ./server
    ports:
      - 8000:5000
    volumes:
      - /app/node_modules
      - ./server:/app
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
  client:
    build: 
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    restart: always
    environment:
      - WDS_SOCKET_PORT=0
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    restart: always
  nginx:
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    restart: always
    ports:
      - 8080:80
