version: '3.8'
services:
  api:
    image: "nguyenduynghi2001/nghi-multi-api"
    mem_limit: 128m
    environment:
      - REDIS_HOST=docker-multi.wd9mvx.ng.0001.use1.cache.amazonaws.com
      - REDIS_PORT=6379
      - PGUSER=postgrest
      - PGHOST=multi-docker-postgres.cw4oevoa0r0s.us-east-1.rds.amazonaws.com
      - PGDATABASE=postgrest
      - PGPASSWORD=postgrest
      - PGPORT=5432
    env_file:
      - .env
  client:
    image: "nguyenduynghi2001/nghi-multi-client"
    mem_limit: 128m
    environment:
      - WDS_SOCKET_PORT=0
  worker:
    image: "nguyenduynghi2001/nghi-multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "nguyenduynghi2001/nghi-multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
